-- ENHANCED LABORATORY MANAGEMENT
-- Extended laboratory functionality for better workflow, imaging requests, and technician management

-- Enhanced imaging requests with better status tracking
CREATE TABLE imaging_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  patient_id INT NOT NULL,
  prescribing_medecin_id INT NOT NULL,
  type_imagerie_id INT NOT NULL,
  requesting_institution_id INT DEFAULT NULL,
  performing_laboratory_id INT DEFAULT NULL,
  request_date DATETIME NOT NULL,
  scheduled_date DATETIME,
  completed_date DATETIME,
  priority ENUM('routine', 'urgent', 'stat', 'emergency') DEFAULT 'routine',
  clinical_indication TEXT NOT NULL,
  patient_preparation_instructions TEXT,
  contrast_required BOOLEAN DEFAULT FALSE,
  contrast_type VARCHAR(100),
  special_instructions TEXT,
  request_status ENUM('requested', 'scheduled', 'in_progress', 'completed', 'cancelled', 'no_show') DEFAULT 'requested',
  technician_assigned_id INT DEFAULT NULL,
  radiologist_assigned_id INT DEFAULT NULL,
  equipment_used VARCHAR(100),
  study_instance_uid VARCHAR(255), -- DICOM identifier
  accession_number VARCHAR(50),
  referring_physician_notes TEXT,
  patient_history_relevant TEXT,
  allergies_contrast BOOLEAN DEFAULT FALSE,
  pregnancy_status ENUM('unknown', 'not_pregnant', 'pregnant', 'possibly_pregnant') DEFAULT 'unknown',
  created_by_user_id INT NOT NULL,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  date_modified DATETIME DEFAULT NULL,
  FOREIGN KEY (patient_id) REFERENCES patients(id),
  FOREIGN KEY (prescribing_medecin_id) REFERENCES medecins(id),
  FOREIGN KEY (type_imagerie_id) REFERENCES types_imagerie(id),
  FOREIGN KEY (requesting_institution_id) REFERENCES institutions(id),
  FOREIGN KEY (performing_laboratory_id) REFERENCES institutions(id),
  FOREIGN KEY (technician_assigned_id) REFERENCES utilisateurs(id),
  FOREIGN KEY (radiologist_assigned_id) REFERENCES medecins(id),
  FOREIGN KEY (created_by_user_id) REFERENCES utilisateurs(id),
  INDEX idx_imaging_requests_patient (patient_id),
  INDEX idx_imaging_requests_status (request_status),
  INDEX idx_imaging_requests_laboratory (performing_laboratory_id),
  INDEX idx_imaging_requests_priority (priority),
  INDEX idx_imaging_requests_date (request_date)
);

-- Laboratory technician assignments and specializations
CREATE TABLE laboratory_technicians (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  laboratory_id INT NOT NULL,
  employee_id VARCHAR(50),
  specializations JSON, -- Array of specializations like ["hematology", "biochemistry", "microbiology"]
  certifications JSON, -- Array of certifications
  shift_schedule JSON, -- Weekly schedule
  is_active BOOLEAN DEFAULT TRUE,
  hire_date DATE,
  supervisor_id INT DEFAULT NULL,
  access_level ENUM('basic', 'advanced', 'supervisor', 'manager') DEFAULT 'basic',
  can_validate_results BOOLEAN DEFAULT FALSE,
  max_concurrent_tests INT DEFAULT 10,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES utilisateurs(id),
  FOREIGN KEY (laboratory_id) REFERENCES institutions(id),
  FOREIGN KEY (supervisor_id) REFERENCES laboratory_technicians(id),
  UNIQUE KEY unique_user_laboratory (user_id, laboratory_id),
  INDEX idx_laboratory_technicians_laboratory (laboratory_id),
  INDEX idx_laboratory_technicians_active (is_active),
  INDEX idx_laboratory_technicians_specializations (specializations(255))
);

-- Enhanced analysis workflow tracking
CREATE TABLE analysis_workflow (
  id INT AUTO_INCREMENT PRIMARY KEY,
  analysis_request_id INT NOT NULL, -- References resultats_analyses(id)
  patient_id INT NOT NULL,
  laboratory_id INT NOT NULL,
  workflow_step ENUM('received', 'sample_prep', 'testing', 'quality_control', 'validation', 'reporting', 'completed') NOT NULL,
  step_status ENUM('pending', 'in_progress', 'completed', 'failed', 'skipped') DEFAULT 'pending',
  assigned_technician_id INT DEFAULT NULL,
  step_start_time DATETIME,
  step_end_time DATETIME,
  duration_minutes INT,
  equipment_used VARCHAR(100),
  reagent_batch VARCHAR(50),
  quality_control_passed BOOLEAN DEFAULT NULL,
  step_notes TEXT,
  error_code VARCHAR(50),
  error_description TEXT,
  supervisor_review_required BOOLEAN DEFAULT FALSE,
  supervisor_reviewed_by INT DEFAULT NULL,
  supervisor_review_date DATETIME,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (analysis_request_id) REFERENCES resultats_analyses(id),
  FOREIGN KEY (patient_id) REFERENCES patients(id),
  FOREIGN KEY (laboratory_id) REFERENCES institutions(id),
  FOREIGN KEY (assigned_technician_id) REFERENCES laboratory_technicians(id),
  FOREIGN KEY (supervisor_reviewed_by) REFERENCES laboratory_technicians(id),
  INDEX idx_analysis_workflow_request (analysis_request_id),
  INDEX idx_analysis_workflow_laboratory (laboratory_id),
  INDEX idx_analysis_workflow_step (workflow_step, step_status),
  INDEX idx_analysis_workflow_technician (assigned_technician_id)
);

-- Laboratory equipment management
CREATE TABLE laboratory_equipment (
  id INT AUTO_INCREMENT PRIMARY KEY,
  laboratory_id INT NOT NULL,
  equipment_name VARCHAR(100) NOT NULL,
  equipment_type VARCHAR(100) NOT NULL,
  model VARCHAR(100),
  serial_number VARCHAR(100),
  manufacturer VARCHAR(100),
  installation_date DATE,
  last_maintenance_date DATE,
  next_maintenance_date DATE,
  calibration_date DATE,
  next_calibration_date DATE,
  status ENUM('operational', 'maintenance', 'out_of_service', 'calibration') DEFAULT 'operational',
  location_in_lab VARCHAR(100),
  supported_test_types JSON, -- Array of test types this equipment can perform
  maintenance_notes TEXT,
  warranty_expiry_date DATE,
  service_contract_info TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  FOREIGN KEY (laboratory_id) REFERENCES institutions(id),
  INDEX idx_laboratory_equipment_laboratory (laboratory_id),
  INDEX idx_laboratory_equipment_status (status),
  INDEX idx_laboratory_equipment_maintenance (next_maintenance_date)
);

-- Sample tracking and chain of custody
CREATE TABLE sample_tracking (
  id INT AUTO_INCREMENT PRIMARY KEY,
  analysis_request_id INT NOT NULL,
  patient_id INT NOT NULL,
  sample_id VARCHAR(50) NOT NULL,
  sample_type ENUM('blood', 'urine', 'stool', 'saliva', 'tissue', 'swab', 'other') NOT NULL,
  collection_date DATETIME NOT NULL,
  collection_site VARCHAR(100),
  collected_by_user_id INT,
  collection_method VARCHAR(100),
  sample_volume DECIMAL(8,2),
  sample_unit VARCHAR(20),
  container_type VARCHAR(50),
  preservation_method VARCHAR(100),
  transport_conditions VARCHAR(100),
  received_at_lab_date DATETIME,
  received_by_technician_id INT,
  sample_condition_on_receipt ENUM('good', 'acceptable', 'poor', 'rejected') DEFAULT 'good',
  rejection_reason TEXT,
  storage_location VARCHAR(100),
  storage_temperature DECIMAL(5,2),
  expiry_date DATETIME,
  disposal_date DATETIME,
  chain_of_custody_notes TEXT,
  barcode VARCHAR(100),
  FOREIGN KEY (analysis_request_id) REFERENCES resultats_analyses(id),
  FOREIGN KEY (patient_id) REFERENCES patients(id),
  FOREIGN KEY (collected_by_user_id) REFERENCES utilisateurs(id),
  FOREIGN KEY (received_by_technician_id) REFERENCES laboratory_technicians(id),
  UNIQUE KEY unique_sample_id (sample_id),
  INDEX idx_sample_tracking_analysis (analysis_request_id),
  INDEX idx_sample_tracking_patient (patient_id),
  INDEX idx_sample_tracking_collection_date (collection_date),
  INDEX idx_sample_tracking_barcode (barcode)
);

-- Laboratory quality control
CREATE TABLE laboratory_quality_control (
  id INT AUTO_INCREMENT PRIMARY KEY,
  laboratory_id INT NOT NULL,
  test_type_id INT NOT NULL,
  control_type ENUM('internal', 'external', 'proficiency') NOT NULL,
  control_date DATE NOT NULL,
  control_batch VARCHAR(50),
  expected_value DECIMAL(10,3),
  actual_value DECIMAL(10,3),
  acceptable_range_min DECIMAL(10,3),
  acceptable_range_max DECIMAL(10,3),
  result_status ENUM('pass', 'fail', 'warning') NOT NULL,
  deviation_percentage DECIMAL(5,2),
  corrective_action_required BOOLEAN DEFAULT FALSE,
  corrective_action_taken TEXT,
  technician_id INT NOT NULL,
  supervisor_reviewed BOOLEAN DEFAULT FALSE,
  supervisor_id INT DEFAULT NULL,
  equipment_used VARCHAR(100),
  reagent_lot VARCHAR(50),
  environmental_conditions TEXT,
  notes TEXT,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (laboratory_id) REFERENCES institutions(id),
  FOREIGN KEY (test_type_id) REFERENCES types_analyses(id),
  FOREIGN KEY (technician_id) REFERENCES laboratory_technicians(id),
  FOREIGN KEY (supervisor_id) REFERENCES laboratory_technicians(id),
  INDEX idx_laboratory_qc_laboratory (laboratory_id),
  INDEX idx_laboratory_qc_test_type (test_type_id),
  INDEX idx_laboratory_qc_date (control_date),
  INDEX idx_laboratory_qc_status (result_status)
);
