-- Add comprehensive medical specialties to the database
-- This includes all major medical specialties commonly found in hospitals

-- First, let's add more specialties to cover comprehensive medical practice
INSERT IGNORE INTO specialites (nom, description) VALUES
-- Basic specialties (may already exist)
('Médecine générale', 'Médecine de premier recours et suivi global du patient'),
('Cardiologie', 'Spécialité médicale traitant des troubles du cœur et du système cardiovasculaire'),
('Pédiatrie', 'Spécialité médicale consacrée aux enfants et à leurs maladies'),
('Gynécologie-Obstétrique', 'Spécialité médicale qui s\'occupe de la santé du système reproducteur féminin et du suivi de grossesse'),
('Dermatologie', 'Spécialité médicale qui s\'occupe de la peau, des muqueuses et des phanères'),
('Ophtalmologie', 'Spécialité médicale concernant les yeux et la vision'),
('Orthopédie', 'Spécialité chirurgicale qui traite les troubles du système musculo-squelettique'),
('Neurologie', 'Spécialité médicale traitant des troubles du système nerveux'),
('Psychiatrie', 'Spécialité médicale traitant des troubles mentaux'),
('Radiologie', 'Spécialité médicale utilisant l\'imagerie pour diagnostiquer les maladies'),

-- Additional comprehensive specialties
('Anesthésie-Réanimation', 'Spécialité médicale de l\'anesthésie et de la réanimation'),
('Chirurgie générale', 'Spécialité chirurgicale traitant diverses pathologies nécessitant une intervention chirurgicale'),
('Chirurgie cardiaque', 'Spécialité chirurgicale du cœur et des gros vaisseaux'),
('Chirurgie thoracique', 'Spécialité chirurgicale du thorax et des poumons'),
('Chirurgie vasculaire', 'Spécialité chirurgicale des vaisseaux sanguins'),
('Chirurgie plastique', 'Spécialité chirurgicale de reconstruction et d\'esthétique'),
('Neurochirurgie', 'Spécialité chirurgicale du système nerveux'),
('Urologie', 'Spécialité médicale et chirurgicale de l\'appareil urinaire et génital masculin'),
('ORL (Oto-Rhino-Laryngologie)', 'Spécialité médicale et chirurgicale de l\'oreille, du nez et de la gorge'),
('Gastroentérologie', 'Spécialité médicale de l\'appareil digestif'),
('Pneumologie', 'Spécialité médicale de l\'appareil respiratoire'),
('Endocrinologie', 'Spécialité médicale des hormones et du métabolisme'),
('Rhumatologie', 'Spécialité médicale des articulations et des os'),
('Hématologie', 'Spécialité médicale du sang et des organes hématopoïétiques'),
('Oncologie', 'Spécialité médicale du cancer'),
('Néphrologie', 'Spécialité médicale des reins'),
('Médecine interne', 'Spécialité médicale globale de l\'adulte'),
('Gériatrie', 'Spécialité médicale des personnes âgées'),
('Médecine d\'urgence', 'Spécialité médicale des urgences et soins critiques'),
('Médecine du travail', 'Spécialité médicale de la santé au travail'),
('Médecine légale', 'Spécialité médicale appliquée au droit'),
('Anatomie pathologique', 'Spécialité médicale de l\'étude des tissus et cellules'),
('Biologie médicale', 'Spécialité des analyses biologiques et diagnostics'),
('Médecine nucléaire', 'Spécialité médicale utilisant les isotopes radioactifs'),
('Radiothérapie', 'Spécialité médicale du traitement par radiations'),
('Immunologie', 'Spécialité médicale du système immunitaire'),
('Génétique médicale', 'Spécialité médicale des maladies génétiques'),
('Médecine physique et réadaptation', 'Spécialité de la rééducation et réadaptation'),
('Allergologie', 'Spécialité médicale des allergies'),
('Infectiologie', 'Spécialité médicale des maladies infectieuses'),
('Toxicologie', 'Spécialité médicale des intoxications'),
('Médecine tropicale', 'Spécialité médicale des maladies tropicales'),
('Pédopsychiatrie', 'Spécialité psychiatrique de l\'enfant et de l\'adolescent'),
('Chirurgie pédiatrique', 'Spécialité chirurgicale de l\'enfant'),
('Médecine d\'urgence pédiatrique', 'Spécialité des urgences pédiatriques'),
('Néonatologie', 'Spécialité médicale du nouveau-né'),
('Médecine fœtale', 'Spécialité médicale du fœtus'),
('Andrologie', 'Spécialité médicale de la santé masculine'),
('Sénologie', 'Spécialité médicale du sein'),
('Proctologie', 'Spécialité médicale et chirurgicale du rectum et de l\'anus'),
('Phlébologie', 'Spécialité médicale des veines'),
('Médecine esthétique', 'Spécialité médicale de l\'esthétique non chirurgicale'),
('Homéopathie', 'Médecine alternative homéopathique'),
('Acupuncture', 'Médecine alternative par acupuncture'),
('Ostéopathie', 'Médecine manuelle ostéopathique'),
('Diététique', 'Spécialité de la nutrition et de l\'alimentation'),
('Podologie', 'Spécialité médicale du pied'),
('Stomatologie', 'Spécialité médicale et chirurgicale de la bouche'),
('Chirurgie maxillo-faciale', 'Spécialité chirurgicale de la face et des mâchoires'),
('Médecine hyperbare', 'Spécialité médicale de l\'oxygénothérapie hyperbare'),
('Médecine du sport', 'Spécialité médicale du sport et de l\'activité physique'),
('Tabacologie', 'Spécialité médicale du sevrage tabagique'),
('Addictologie', 'Spécialité médicale des addictions'),
('Soins palliatifs', 'Spécialité médicale des soins de fin de vie'),
('Médecine de la douleur', 'Spécialité médicale de la prise en charge de la douleur'); 