const moroccanCities = [
  "Agadir",
  "Al Hoceima",
  "Asilah",
  "Azemmour",
  "Azrou",
  "Beni Mellal",
  "Berkane",
  "Berrechid",
  "Boujdour",
  "Casablanca",
  "Chefchaouen",
  "Dakhla",
  "El Jadida",
  "El Kelaa des Sraghna",
  "Errachidia",
  "Essaouira",
  "Fès",
  "Figuig",
  "Fnideq",
  "Guelmim",
  "Ifrane",
  "Kénitra",
  "Khemisset",
  "Khenifra",
  "Khouribga",
  "Ksar El Kebir",
  "Laâyoune",
  "Larache",
  "Marrakech",
  "Martil",
  "Meknès",
  "Mohammedia",
  "Nador",
  "Ouarzazate",
  "Ouazzane",
  "Oujda",
  "Rabat",
  "Safi",
  "Salé",
  "Sefrou",
  "Settat",
  "Sidi Ifni",
  "Sidi Kacem",
  "Sidi Slimane",
  "Tanger",
  "Tan-Tan",
  "Taounate",
  "Taroudant",
  "Taza",
  "Tétouan",
  "Tiznit",
];

export default moroccanCities; 